
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mahesh V
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        
        initComponents();
        jPanel2.setVisible(false);
           jPanel3.setVisible(false);
             jPanel4.setVisible(false);
        sid.setVisible(false);
        fname.setVisible(false);
        lname.setVisible(false);
        dept.setVisible(false);
        courseids.setVisible(false);
        fid.setVisible(false);
        name2.setVisible(false);
        name3.setVisible(false);
        fdept.setVisible(false);
        fcourse.setVisible(false);
        fclass.setVisible(false);
       sfname.setVisible(false);
          jLabel9.setVisible(false);
           jLabel10.setVisible(false);
            jLabel5.setVisible(false);
             jLabel14.setVisible(false);
              jLabel11.setVisible(false);
               jLabel16.setVisible(false);
                jLabel12.setVisible(false);
                 jLabel13.setVisible(false);
                  jLabel8.setVisible(false);
                  jLabel17.setVisible(false);
                  update1.setVisible(false);
           update3.setVisible(false);
                  jLabel3.setVisible(false);
                  jTextField5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        courseids = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        dept = new javax.swing.JTextField();
        sid = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sfname = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        update1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        name2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        name3 = new javax.swing.JTextField();
        fdept = new javax.swing.JTextField();
        fcourse = new javax.swing.JTextField();
        fclass = new javax.swing.JTextField();
        fid = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        update3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 0));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mailsend.JPG"))); // NOI18N
        jLabel23.setText("Send an Email ");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 50));

        jPanel1.setBackground(new java.awt.Color(249, 204, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Admin");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar-clock.JPG"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student Details", "Faculty Details", "Course Details", "Add TimeTable", "Add a Class", "Add Exam Details" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 180, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout1.JPG"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 60, 60));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("Reset All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 720, 130, 50));

        jPanel4.setBackground(new java.awt.Color(253, 250, 223));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Course", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("CourseID");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Semester");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Credits");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 90, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("CourseName");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, 30));
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 150, 30));
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 150, 30));
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 150, 30));
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 140, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.JPG"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 100, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remove.JPG"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 90, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 500, 260));

        jPanel2.setBackground(new java.awt.Color(228, 211, 170));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update/Insert Student Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("C_ID ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 70, 40));
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 200, 30));
        jPanel2.add(courseids, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("L_Name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Dept");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ClassId");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 200, 30));
        jPanel2.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 200, 30));
        jPanel2.add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 200, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin2.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 210, 230));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("S_ID ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 40));

        sfname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sfname.setText("F_Name");
        jPanel2.add(sfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 40));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add/Update Student", "Remove Student", "Add Course", "Assign Student Class" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 30));

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.JPG"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 110, 40));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 150, 30));

        update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.JPG"))); // NOI18N
        update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update1MouseClicked(evt);
            }
        });
        jPanel2.add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 550, 400));

        jPanel3.setBackground(new java.awt.Color(253, 228, 177));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update/Insert Faculty Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Course_Id");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, 40));
        jPanel3.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 230, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("LName");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Dept");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("F_ID ");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("FName");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("ClassId");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 70, 40));
        jPanel3.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 230, 30));
        jPanel3.add(fdept, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 230, 30));
        jPanel3.add(fcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 230, 30));
        jPanel3.add(fclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 230, 30));
        jPanel3.add(fid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 230, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin2.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 220, 200));

        jButton7.setBackground(new java.awt.Color(204, 153, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.JPG"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 110, 40));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add Faculty Course", "Add/Update Faculty Info", "Remove Faculty" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 40));

        update3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.JPG"))); // NOI18N
        update3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update3MouseClicked(evt);
            }
        });
        jPanel3.add(update3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 80, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 510, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 780));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
new process().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       if(jComboBox1.getSelectedIndex()==0)
       {
             
            
           jPanel2.setVisible(true);
           jPanel3.setVisible(false);
             jPanel4.setVisible(false);
            sid.setVisible(false);
        fname.setVisible(false);
        lname.setVisible(false);
        dept.setVisible(false);
        courseids.setVisible(false);
        fid.setVisible(false);
        name2.setVisible(false);
        name3.setVisible(false);
        fdept.setVisible(false);
        fcourse.setVisible(false);
        fclass.setVisible(false);
       sfname.setVisible(false);
          jLabel9.setVisible(false);
           jLabel10.setVisible(false);
            jLabel5.setVisible(false);
             jLabel14.setVisible(false);
              jLabel11.setVisible(false);
               jLabel16.setVisible(false);
                jLabel12.setVisible(false);
                 jLabel13.setVisible(false);
                  jLabel8.setVisible(false);
                  jLabel17.setVisible(false);
       }
       else if(jComboBox1.getSelectedIndex()==1)
       {
               
           for (int i = 0; i <= 20; i++) {
               
                 try {
                 
                     Thread.sleep(5);
                   
                     
                 } catch (InterruptedException ex) {
                     Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
           
          jPanel3.setVisible(true);
           jPanel2.setVisible(false); 
             jPanel4.setVisible(false);
            sid.setVisible(false);
        fname.setVisible(false);
        lname.setVisible(false);
        dept.setVisible(false);
        courseids.setVisible(false);
        fid.setVisible(false);
        name2.setVisible(false);
        name3.setVisible(false);
        fdept.setVisible(false);
        fcourse.setVisible(false);
        fclass.setVisible(false);
       sfname.setVisible(false);
          jLabel9.setVisible(false);
          jLabel3.setVisible(false);
          jTextField5.setVisible(false);
           jLabel10.setVisible(false);
            jLabel5.setVisible(false);
             jLabel14.setVisible(false);
              jLabel11.setVisible(false);
               jLabel16.setVisible(false);
                jLabel12.setVisible(false);
                 jLabel13.setVisible(false);
                  jLabel8.setVisible(false);
                  jLabel17.setVisible(false);
       }
             else if(jComboBox1.getSelectedIndex()==2)
             {
                 jPanel4.setVisible(true);
                 jPanel3.setVisible(false);
                 jPanel2.setVisible(false);
             }
             else if (jComboBox1.getSelectedIndex()==3)
             {
                 new SetTT().setVisible(true);
                 this.dispose();
             }
               else if(jComboBox1.getSelectedIndex()==4)
               {
                   new Class().setVisible(true);
                   this.dispose();
               }
               else if(jComboBox1.getSelectedIndex()==5)
               {
                   new addExam().setVisible(true);
                   this.dispose();
               }
       
       else
             {
                  JOptionPane.showMessageDialog(this, " Index Access Error  ", "Index Not Selected", JOptionPane.WARNING_MESSAGE);
             }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
      if(jComboBox2.getSelectedIndex()==0)
      {
           update1.setVisible(true);jLabel15.setVisible(false);
       sid.setVisible(true);
       fname.setVisible(true);
       lname.setVisible(true);
       dept.setVisible(true);
          jLabel11.setVisible(true); 
             sfname.setVisible(true); 
                jLabel9.setVisible(true); 
                   jLabel10.setVisible(true); 
                       jLabel5.setVisible(false);
                       courseids.setVisible(false);
                       jLabel3.setVisible(false);
                  jTextField5.setVisible(false);
      }
      else if(jComboBox2.getSelectedIndex()==1)
      {
          update1.setVisible(false);  jLabel15.setVisible(true);  
        sid.setVisible(true);
        jLabel11.setVisible(true);
        fname.setVisible(false);
        lname.setVisible(false);
        dept.setVisible(false);
        courseids.setVisible(false);
       sfname.setVisible(false);
          jLabel9.setVisible(false);
           jLabel10.setVisible(false);
            jLabel5.setVisible(false);
            jLabel3.setVisible(false);
                  jTextField5.setVisible(false);
      }
       else if(jComboBox2.getSelectedIndex()==2)
      {
           update1.setVisible(false); jLabel15.setVisible(true);   
        sid.setVisible(true);
 courseids.setVisible(true); 
        fname.setVisible(false);
        lname.setVisible(false);
        dept.setVisible(false);
       
       sfname.setVisible(false);
          jLabel9.setVisible(false);
           jLabel10.setVisible(false);
            jLabel5.setVisible(true);
           
              jLabel11.setVisible(true);
              jLabel3.setVisible(false);
                  jTextField5.setVisible(false);
      }
       else if(jComboBox2.getSelectedIndex()==3)
      {
          update1.setVisible(false);  jLabel15.setVisible(true);   
        sid.setVisible(true);
 courseids.setVisible(false); 
        fname.setVisible(false);
        lname.setVisible(false);
        dept.setVisible(false);
       
       sfname.setVisible(false);
          jLabel9.setVisible(false);
           jLabel10.setVisible(false);
            jLabel5.setVisible(false);
           
              jLabel11.setVisible(true);
              jLabel3.setVisible(true);
                  jTextField5.setVisible(true);
      }
      else
       {
         update1.setVisible(false);   
       }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String a=sid.getText();
String b=fname.getText();
String c=lname.getText();
String d=dept.getText();
String cs=courseids.getText();
String cl=jTextField5.getText();


if(jComboBox2.getSelectedIndex()==0)
{


   try
{
     if(!a.isEmpty() &&!b.isEmpty() && !c.isEmpty() && !d.isEmpty() )
 {
     java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
    String query= "INSERT INTO student VALUES( '"+a+"','"+b+"','"+c+"','"+d+"');";
    stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(this, " Successfully Inserted! ");
 }
     else
     {
         JOptionPane.showMessageDialog(this, " Please Enter The Details ", "Details Not Filled", JOptionPane.WARNING_MESSAGE);
     }
     
     
     
     
}      
catch (Exception e) {
     JOptionPane.showMessageDialog(this,e.getMessage());       
        }     
}



else if(jComboBox2.getSelectedIndex()==1)
{
    if(!a.isEmpty())
    {
       try {
            java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
             String query3 = "Delete  From student_course_reg Where sid= '"+a+"' ;";
              String query4 = "Delete  From exam_reg Where sid= '"+a+"' ;";
            String query2 = "Delete  From student_class Where sid= '"+a+"' ;";
            String query = "Delete  From student Where sid= '"+a+"' ;";
            stmt.executeUpdate(query3);
            stmt.executeUpdate(query2);
             stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this, " Successfully Deleted! ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }     
    }
     else
     {
         JOptionPane.showMessageDialog(this, " Please Enter The Details ", "Details Not Filled", JOptionPane.WARNING_MESSAGE);
     }
}

else if(jComboBox2.getSelectedIndex()==2)
{
     if(!a.isEmpty()&&!cs.isEmpty())
    {
          try
{

     java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
    
    String query= "INSERT INTO student_course_reg VALUES( '"+a+"','"+cs+"');";
    stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(this, " Successfully Inserted! ");
 }
    
     
catch (Exception e) {
     JOptionPane.showMessageDialog(this,e.getMessage());       
        }     
 
    }
     else
     {
         JOptionPane.showMessageDialog(this, " Please Enter The Details ", "Details Not Filled", JOptionPane.WARNING_MESSAGE);
     }
}


else if(jComboBox2.getSelectedIndex()==3)
{
     if(!a.isEmpty()&&!cl.isEmpty())
    {
          try
{
 java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
    String query= "INSERT INTO student_class VALUES( '"+a+"','"+cl+"');";
    stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(this, " Successfully Inserted! ");
 }
    
     
catch (Exception e) {
     JOptionPane.showMessageDialog(this,e.getMessage());       
        }     
 
    }
     else
     {
         JOptionPane.showMessageDialog(this, " Please Enter The Details ", "Details Not Filled", JOptionPane.WARNING_MESSAGE);
     }
}


   else
 {
     JOptionPane.showMessageDialog(this, " Select Valid Index! ", "Details Not Filled", JOptionPane.WARNING_MESSAGE);
 }
           
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
String a=fid.getText();
String b=name2.getText();
String c=name3.getText();
String d=fdept.getText();
String f=fcourse.getText();
String g=fclass.getText();
        
if(jComboBox3.getSelectedIndex()==0&&!a.isEmpty()&&!f.isEmpty()&&!g.isEmpty())
{
      try
{

    java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
    String query= "INSERT INTO faculty_class VALUES( '"+a+"','"+f+"','"+g+"');";
    stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(this, " Successfully Inserted! ");
 }
    
     
catch (Exception e) {
     JOptionPane.showMessageDialog(this,e.getMessage());       
        }     
 
    
}

else if(jComboBox3.getSelectedIndex()==1&&!a.isEmpty()&&!b.isEmpty()&&!c.isEmpty()&&!d.isEmpty())
{
    try
{

   java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
    String query= "INSERT INTO faculty VALUES( '"+a+"','"+b+"','"+c+"','"+d+"');";
    stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(this, " Successfully Inserted! ");
 }
    
     
catch (Exception e) {
     JOptionPane.showMessageDialog(this,e.getMessage());       
        }    
}

else if(jComboBox3.getSelectedIndex()==2&&!a.isEmpty())
{
     try {
            java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
                String query2 = "Delete  From faculty_class Where fid= '"+a+"' ;";
            String query3 = "Delete  From faculty_timetable Where fid= '"+a+"' ;";
            String query = "Delete  From faculty Where fid= '"+a+"' ;";
            stmt.executeUpdate(query2);
          stmt.executeUpdate(query3);
          stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this, " Row Deleted if Present! ");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }     
    
    
}
else{
      JOptionPane.showMessageDialog(this, " Enter Valid Details! ");
}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
      if(jComboBox3.getSelectedIndex()==0)
      {
                update3.setVisible(false); jLabel18.setVisible(true);    
          jLabel14.setVisible(true);    
             jLabel8.setVisible(true);    
                jLabel17.setVisible(true);    
                jLabel16.setVisible(false);    
                jLabel12.setVisible(false);    
                jLabel13.setVisible(false); 
                fid.setVisible(true);
                fcourse.setVisible(true);
                fclass.setVisible(true);
                name2.setVisible(false);name3.setVisible(false);fdept.setVisible(false);  
      }
      else if(jComboBox3.getSelectedIndex()==1)
      {
        jLabel18.setVisible(true); 
      update3.setVisible(true);
        fid.setVisible(true);
        name2.setVisible(true);
        name3.setVisible(true);
        fdept.setVisible(true);
        fcourse.setVisible(false);
        fclass.setVisible(false);

               jLabel14.setVisible(true);
               jLabel16.setVisible(true);
               jLabel12.setVisible(true);
               jLabel13.setVisible(true);
               jLabel8.setVisible(false);
               jLabel17.setVisible(false);  
      }
       else if(jComboBox3.getSelectedIndex()==2)
       {
           jLabel18.setVisible(true); 
        fid.setVisible(true);
        jLabel14.setVisible(true);
              update3.setVisible(false);
          name2.setVisible(false);
        name3.setVisible(false);
        fdept.setVisible(false);
        fcourse.setVisible(false);
        fclass.setVisible(false);

               jLabel16.setVisible(false);
               jLabel12.setVisible(false);
               jLabel13.setVisible(false);
               
               jLabel17.setVisible(false);  
        
        
       }
      else
      {
           JOptionPane.showMessageDialog(this, " Select Valid Index! ", "Details Not Filled", JOptionPane.WARNING_MESSAGE);
      }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String a=jTextField1.getText();
      String b=jTextField2.getText();
       String c=jTextField3.getText();
        String d=jTextField4.getText();
        if(!a.isEmpty()&&!b.isEmpty()&&!c.isEmpty()&&!d.isEmpty())
        {
             try
{

    java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
    String query= "INSERT INTO course VALUES( '"+a+"','"+b+"','"+d+"','"+c+"');";
    stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(this, " Successfully Inserted! ");
 }
    
     
catch (Exception e) {
     JOptionPane.showMessageDialog(this,e.getMessage());       
        }      
        }
        else{
           JOptionPane.showMessageDialog(this, " No Input ", "Details Not Filled", JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit Application",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
System.exit(0);
} 
else {
  this.setVisible(true);
}       
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
      this.dispose();
      new SendingEmail().setVisible(true);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 jPanel2.setVisible(false);
           jPanel3.setVisible(false);
             jPanel4.setVisible(false);
             sid.setText("");
             fname.setText("");
             lname.setText("");
             dept.setText("");
             courseids.setText("");
             fid.setText("");
             name2.setText("");
             name3.setText("");
             fdept.setText("");
             fcourse.setText("");
             fclass.setText("");
             jTextField5.setText(""); 
             jTextField4.setText("");
             jTextField3.setText("");
             jTextField2.setText("");
             jTextField1.setText("");
             
        sid.setVisible(false);
        fname.setVisible(false);
        lname.setVisible(false);
        dept.setVisible(false);
        courseids.setVisible(false);
        fid.setVisible(false);
        name2.setVisible(false);
        name3.setVisible(false);
        fdept.setVisible(false);
        fcourse.setVisible(false);
        fclass.setVisible(false);
       sfname.setVisible(false);
          jLabel9.setVisible(false);
           jLabel10.setVisible(false);
            jLabel5.setVisible(false);
             jLabel14.setVisible(false);
              jLabel11.setVisible(false);
               jLabel16.setVisible(false);
                jLabel12.setVisible(false);
                 jLabel13.setVisible(false);
                  jLabel8.setVisible(false);
                  jLabel17.setVisible(false);
          
                  jLabel3.setVisible(false);
                  jTextField5.setVisible(false);        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
String csid=jTextField1.getText();
       if(csid.isEmpty())
       {
          JOptionPane.showMessageDialog(this,"Please enter the CourseID"); 
       }
       else
       {
        try {
            java.lang.Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
            Statement stmt = (Statement) con.createStatement();
            
            String query2 = "Delete  From exam_course Where courseid='"+csid+"';";
            String query3 = "Delete  From exam_reg Where courseid='"+csid+"';";
            String query4 = "Delete  From student_course_reg Where courseid='"+csid+"';";
            String query5 = "Delete  From faculty_timetable Where courseid='"+csid+"';";
            String query6 = "Delete  From student_timetable Where courseid='"+csid+"';";
            String query7 = "Delete  From faculty_class Where courseid='"+csid+"';";
            String query8 = "Delete  From exam_course Where courseid='"+csid+"';";
            
            String query = "Delete  From course Where courseid='"+csid+"';";
           stmt.executeUpdate(query2);
             stmt.executeUpdate(query3);
              stmt.executeUpdate(query4);
               stmt.executeUpdate(query5);
                stmt.executeUpdate(query6);
                 stmt.executeUpdate(query7);
                  stmt.executeUpdate(query8);
                   stmt.executeUpdate(query);
                   
            JOptionPane.showMessageDialog(this,"Row removed if it existed!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void update1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update1MouseClicked

        String a=sid.getText();
String b=fname.getText();
String c=lname.getText();
String d=dept.getText();
String cs=courseids.getText();
String cl=jTextField5.getText();
if(!a.isEmpty()&&!b.isEmpty()&&!c.isEmpty()&&!d.isEmpty())
    {
       try {
            java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
                
                
        
            String query4 = "Update  student set fname='"+b+"', lname='"+c+"',dept='"+d+"' Where sid= '"+a+"' ;";
         
             stmt.executeUpdate(query4);
            JOptionPane.showMessageDialog(this, " Successfully Updated if row present! ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }     
    }
     else
     {
         JOptionPane.showMessageDialog(this, " Please Enter the Details ", "Details Not Filled", JOptionPane.WARNING_MESSAGE);
     }  
    }//GEN-LAST:event_update1MouseClicked

    private void update3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update3MouseClicked
String a=fid.getText();
String b=name2.getText();
String c=name3.getText();
String d=fdept.getText();
if(!a.isEmpty()&&!b.isEmpty()&&!c.isEmpty()&&!d.isEmpty())
{
    try
{

   java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
    String query= "Update faculty set fname='"+b+"', lname='"+c+"',dept='"+d+"' Where fid= '"+a+"'";
    stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(this, " Successfully Updated if row present! ");
 }
    
     
catch (Exception e) {
     JOptionPane.showMessageDialog(this,e.getMessage());       
        }    
}       // TODO add your handling code here:
    }//GEN-LAST:event_update3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField courseids;
    private javax.swing.JTextField dept;
    private javax.swing.JTextField fclass;
    private javax.swing.JTextField fcourse;
    private javax.swing.JTextField fdept;
    private javax.swing.JTextField fid;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField name3;
    private javax.swing.JLabel sfname;
    private javax.swing.JTextField sid;
    private javax.swing.JLabel update1;
    private javax.swing.JLabel update3;
    // End of variables declaration//GEN-END:variables
}
