
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mahesh V
 */
public class SetTT extends javax.swing.JFrame {

    /**
     * Creates new form classTT
     */
    public SetTT() {
        initComponents();
        jPanel3.setVisible(false);
         jPanel2.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        remove = new javax.swing.JLabel();
        update1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        remove2 = new javax.swing.JLabel();
        update2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backarrow1.JPG"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setForeground(new java.awt.Color(153, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add Faculty TimeTable", "Add Student TimeTable" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calendar1.JPG"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 70, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Time Table");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 240, 60));

        jPanel2.setBackground(new java.awt.Color(181, 181, 253));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Faculty", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(165, 220, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.JPG"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 110, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CourseId");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ClassId");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("TimeSlot");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("FId");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 30));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 190, 30));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 190, 30));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 190, 30));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 190, 30));

        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remove.JPG"))); // NOI18N
        remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMouseClicked(evt);
            }
        });
        jPanel2.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 80, 30));

        update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update1.JPG"))); // NOI18N
        update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update1MouseClicked(evt);
            }
        });
        jPanel2.add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 40, 30));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 390, 320));

        jPanel3.setBackground(new java.awt.Color(181, 181, 253));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(196, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.JPG"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ClassId");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("CourseId");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("TimeSlot");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 30));
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 190, 30));
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 190, 30));
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 190, 30));

        remove2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remove.JPG"))); // NOI18N
        remove2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remove2MouseClicked(evt);
            }
        });
        jPanel3.add(remove2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 80, 30));

        update2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update1.JPG"))); // NOI18N
        update2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update2MouseClicked(evt);
            }
        });
        jPanel3.add(update2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, 40));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 400, 320));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout1.JPG"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, 70));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
new admin().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
      if(jComboBox2.getSelectedIndex()==0)
{
   jPanel2.setVisible(true); 
     jPanel3.setVisible(false); 
}
else if(jComboBox2.getSelectedIndex()==1)
{
    jPanel2.setVisible(false); 
      jPanel3.setVisible(true); 
}

  else
    {
            
            }  // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   String a=jTextField5.getText();
     String b=jTextField1.getText();
             String c=jTextField2.getText();
                     String d=jTextField3.getText();
                     if(!a.isEmpty()&&!b.isEmpty()&&!c.isEmpty()&&!d.isEmpty())
                     {
                           try
{

      java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
    String query= "INSERT INTO faculty_timetable VALUES( '"+a+"','"+b+"','"+c+"','"+d+"');";
    stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(this, " Successfully Inserted! ");
 }
    
     
catch (Exception e) {
     JOptionPane.showMessageDialog(this,e.getMessage());       
        }    
                     }
                     else
                     {
                         JOptionPane.showMessageDialog(this, " Please enter details");
                     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   String a=jTextField6.getText();
     String b=jTextField7.getText();
             
                     String d=jTextField8.getText();
                       if(!a.isEmpty()&&!b.isEmpty()&&!d.isEmpty())
                     {
                          try {
                java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
    String query= "INSERT INTO student_timetable VALUES( '"+a+"','"+b+"','"+d+"');";
    stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(this, " Successfully Inserted! ");
 }
    
     
catch (Exception e) {
     JOptionPane.showMessageDialog(this,e.getMessage());       
        }    
                     }
                     else
                     {
                         JOptionPane.showMessageDialog(this, " Please enter details");
                     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit Application",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
System.exit(0);
} 
else {
  this.setVisible(true);
}       
    }//GEN-LAST:event_jLabel11MouseClicked

    private void remove2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remove2MouseClicked
     String a=jTextField6.getText();
     String b=jTextField7.getText();
             
                     String d=jTextField8.getText();
                       if(!a.isEmpty()&&!b.isEmpty()&&!d.isEmpty())
                     {
                          try {
                java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
    String query= "Delete from  student_timetable where classid= '"+a+"'AND courseid='"+b+"'AND timeslot='"+d+"';";
    stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(this, " Successfully Deleted! ");
 }
    
     
catch (Exception e) {
     JOptionPane.showMessageDialog(this,e.getMessage());       
        }    
                     }
                     else
                     {
                         JOptionPane.showMessageDialog(this, " Please enter details");
                     }
    }//GEN-LAST:event_remove2MouseClicked

    private void removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseClicked
       String a=jTextField5.getText();
     String b=jTextField1.getText();
             String c=jTextField2.getText();
                     String d=jTextField3.getText();
                     if(!a.isEmpty()&&!b.isEmpty()&&!c.isEmpty()&&!d.isEmpty())
                     {
                           try
{

      java.lang.Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/timetablem", "root", "rootpw");
                Statement stmt = (Statement) con.createStatement();
    String query= "delete from faculty_timetable where fid= '"+a+"'and courseid= '"+b+"'and classid='"+c+"'and timeslot='"+d+"';";
    stmt.executeUpdate(query);
     JOptionPane.showMessageDialog(this, " Successfully Deleted! ");
 }
    
     
catch (Exception e) {
     JOptionPane.showMessageDialog(this,e.getMessage());       
        }    
                     }
                     else
                     {
                         JOptionPane.showMessageDialog(this, " Please enter details");
                     }
    }//GEN-LAST:event_removeMouseClicked

    private void update1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update1MouseClicked
     jTextField5.setText("");
     jTextField1.setText("");
            jTextField2.setText("");
                     jTextField3.setText("");
                   
    }//GEN-LAST:event_update1MouseClicked

    private void update2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update2MouseClicked
      jTextField6.setText("");
     jTextField7.setText("");
            jTextField8.setText("");
    }//GEN-LAST:event_update2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetTT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel remove;
    private javax.swing.JLabel remove2;
    private javax.swing.JLabel update1;
    private javax.swing.JLabel update2;
    // End of variables declaration//GEN-END:variables
}
